"use client";
import { useEffect, useState } from "react";
import { UploadSimple } from "@/lib/ui/icons";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { apiClient } from "@/lib/api/client";
type Row = { title: string; description: string | null; external_id: string | null; value_cents: number | null; source_metadata: Record<string, string> };
function parse(text: string): Row[] { const lines = text.split(/\r?\n/).filter(Boolean); if (lines.length < 2) return []; const split = (s: string) => s.split(",").map(x => x.replace(/^\"|\"$/g, "").trim()); const h = split(lines[0]).map(x => x.toLowerCase()); return lines.slice(1).map(l => { const v = split(l); const r = Object.fromEntries(h.map((x, i) => [x, v[i] ?? ""])); return { title: r.title || r.name || r.lead || "Lead Kommo", description: r.description || null, external_id: r.id || r.external_id || null, value_cents: r.value ? Math.round(Number(r.value.replace(",", ".")) * 100) : null, source_metadata: r }; }); }
export function ImportLeadsClient() { const [pipelines, setPipelines] = useState<any[]>([]), [stages, setStages] = useState<any[]>([]), [pipelineId, setPipelineId] = useState(""), [stageId, setStageId] = useState(""), [leads, setLeads] = useState<Row[]>([]), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
 useEffect(() => { fetch("/api/v1/pipelines").then(r => r.json()).then(r => setPipelines(r.data?.pipelines ?? r.data ?? [])); }, []); useEffect(() => { if (pipelineId) fetch(`/api/v1/pipelines/${pipelineId}/stages`).then(r => r.json()).then(r => setStages(r.data?.stages ?? r.data ?? [])); }, [pipelineId]);
 async function submit() { setBusy(true); try { const r = await apiClient.post<any>("/api/v1/leads/import", { pipeline_id: pipelineId, stage_id: stageId, leads }); setMessage(`${r.data.imported} lead(s) importado(s); ${r.data.skipped} duplicado(s) ignorado(s).`); setLeads([]); } catch (e) { setMessage(e instanceof Error ? e.message : "Falha na importação."); } finally { setBusy(false); } }
 return <main className="mx-auto max-w-4xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Importar leads</h1><p className="mt-1 text-sm text-muted-foreground">Exporte os leads do Kommo em CSV e defina o funil e a etapa de destino.</p></div><Card className="space-y-5 p-6"><div><Label>Arquivo CSV do Kommo</Label><label className="mt-2 flex cursor-pointer items-center gap-3 rounded-md border border-dashed p-5 text-sm"><UploadSimple size={24}/><span>{leads.length ? `${leads.length} lead(s) preparado(s)` : "Selecionar arquivo CSV"}</span><input type="file" accept=".csv" className="sr-only" onChange={e => { const f=e.target.files?.[0]; if(f) f.text().then(t=>setLeads(parse(t))); }}/></label></div><div className="grid gap-4 md:grid-cols-2"><div><Label>Funil de destino</Label><Select value={pipelineId} onValueChange={v=>{setPipelineId(v);setStageId("")}}><SelectTrigger className="mt-2"><SelectValue placeholder="Selecione o funil"/></SelectTrigger><SelectContent>{pipelines.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Etapa de destino</Label><Select value={stageId} onValueChange={setStageId} disabled={!pipelineId}><SelectTrigger className="mt-2"><SelectValue placeholder="Selecione a etapa"/></SelectTrigger><SelectContent>{stages.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></div></div><Button disabled={!leads.length||!stageId||busy} onClick={submit}>{busy?"Importando…":`Importar ${leads.length||"leads"}`}</Button>{message&&<p role="status" className="text-sm">{message}</p>}</Card></main>; }
